spring:
  application:
    name: roamly
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB

roamly:
  cloudinary:
    cloud-name: ${CLOUDINARY_CLOUD_NAME:}
    api-key: ${CLOUDINARY_API_KEY:}
    api-secret: ${CLOUDINARY_API_SECRET:}
    folder: ${CLOUDINARY_FOLDER:linkcute/avatars}

server:
  port: ${SERVER_PORT:8080}
